; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[common]
build_flags =
    -DSOFT_VERSION=\"x.y.z\"
    -DSTREAM_VIDEO_PORT=16385

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf
upload_port = /dev/ttyACM0
board_build.partitions = partitions_map.csv

build_flags =
    -DBOARD_XIAO_ESP32S3
    -DWIFI_MODE
    -DSTREAM_AUDIO
    -DSTREAM_AUDIO_PORT=16386
    -DLEDC_OUTPUT_IO=4
    ;-DDEBUG_ON

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
upload_port = /dev/ttyACM0
board_build.partitions = partitions_map.csv

build_flags =
    ${common.build_flags}
    -DBOARD_ESP32S3_ETH_CAM
    -DETHERNET_MODE
    -DLEDC_OUTPUT_IO=-1
